Fix indentation (#217)

diff --git a/.github/workflows/SphinxBuild.yml b/.github/workflows/SphinxBuild.yml
--- a/.github/workflows/SphinxBuild.yml
+++ b/.github/workflows/SphinxBuild.yml
@@ -57,23 +57,20 @@ jobs:
       - shell: bash -el {0}
         run: ./tools/github_actions_docs.sh
         name: 'Build docs'
-    # Publish built docs to gh-pages branch.
-    # ===============================
-    - name: Commit documentation changes
-      run: |
-        git clone https://github.com/mne-tools/mne-nirs.git --branch gh-pages --single-branch gh-pages
-        cp -r doc/_build/html/* gh-pages/
-        cd gh-pages
-        git config --local user.email "action@github.com"
-        git config --local user.name "Robert Luke"
-        git add .
-        git commit -m "Update documentation" -a || true
-        # The above command will fail if no changes were present, so we ignore
-        # that.
-    - name: Push changes
-      uses: ad-m/github-push-action@master
-      with:
-        branch: gh-pages
-        directory: gh-pages
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-    # ===============================
+      - name: Commit documentation changes
+        run: |
+          git clone https://github.com/mne-tools/mne-nirs.git --branch gh-pages --single-branch gh-pages
+          cp -r doc/_build/html/* gh-pages/
+          cd gh-pages
+          git config --local user.email "action@github.com"
+          git config --local user.name "Robert Luke"
+          git add .
+          git commit -m "Update documentation" -a || true
+          # The above command will fail if no changes were present, so we ignore
+          # that.
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          branch: gh-pages
+          directory: gh-pages
+          github_token: ${{ secrets.GITHUB_TOKEN }}
